#! /bin/bash
#
#$Author: ee364b13 $
#$Date: 2016-01-12 14:48:29 -0500 (Tue, 12 Jan 2016) $
#$Revision: 83968 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364b13/Lab00/Script1 $
#$Id: Script1 83968 2016-01-12 19:48:29Z ee364b13 $

Num_Of_Param=$#
Param_Values=$@
echo "The program received $Num_Of_Param parameters"
echo "The parameters are : "
echo "$Param_Values"
echo "The 2nd parameter is \"$2\""
echo "The 4th parameter is \"$4\""
exit 0
